               <div class="AboutUsTitle"><h1>Terms & Conditions</h1></div>
                <div style="padding:10px; margin-top: 10px;">
                   <p>The use of this website is subject to the following&nbsp;<strong class="BlackColor">Term &amp; Conditions</strong>:</p>
<p><span class="bold">Site and Contents</span><br /><br />The content of the pages of this website is for your general information and use only. It is subject to change without prior notice. Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law. Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.</p>
<p><span class="bold">Ownership</span></p>
<p>This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.</p>
<p>Unauthorized use of this website may give rise to a claim for damages and/or be a criminal offence.</p>
<p>From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).</p>
<p>You may not create a link to this website from another website or document without www.isquaretaxi.in prior written consent. Your use of this website and any dispute arising out of such use of the website is subject to the laws of India or other regulatory authority.</p>
<p><span class="bold">User Content</span></p>
<p>You are prohibited from posting defamatory, obscene, pornographic, profane, threatening or unlawful material in our forums or our user feedback sections.</p>
<p>www.isquaretaxi.in will fully cooperate with any law enforcement authorities or court order requesting or directing www.isquaretaxi.in to disclose the identity of anyone posting such materials.</p>
<p>www.isquaretaxi.in may change, edit, or remove any user material or conversations that are illegal, indecent, obscene or offensive, or that violates www.isquaretaxi.in policies in any way.</p>
<ul id="termslist">
<li>A booking ID No (confirmation) will be sent to the traveller over email when he completes an online car booking with " I SQUARE TAXI " along with an SMS update on the same.</li>
<li>Producing the booking ID No provided earlier is mandatory to avail the car rental services by " I SQUARE TAXI ". If this is not done it entitles the driver to refuse service delivery without any liability to us.</li>
<li>When a customer produces the booking ID No provided to him it earlier, it implies that we have read and understood all terms and conditions mentioned herewith and agrees on all of them.</li>
<li>The start and end distance in Kms will be calculated from travellers pickup place. Driving speed of the vehicle as per the directions of the local transport authority only.<span class="bold"> Parking charges, Toll charges, State Taxes and Entry Fees etc. to be paid by the customer.</span></li>
<li>Distances between two locations (points) be it an intercity distance or from travellers pickup place etc <span class="bold">mentioned on the website are approximate</span>. Actual distance may differ depending on the exact geographical location of the points under consideration.</li>
<li>Car air-conditioner<span class="bold"> will not work on hilly routes &amp; also when the vehicle is not in motion</span>. The customer is also not expected to request the driver to make the air condition operational in the aforementioned cases.</li>
<li>Any form of discounts are only applicable only on the basic fare and cannot be made available on extra charges like toll, taxes, charges on for extra Kms consumed if applicable, charges for extra hours consumed if applicable, driver allowance, parking, night charges, unless specified.</li>
<li>The vehicle booked will be subject to availability. In a case where the car booked is not available on the day of travel the customer will be provided with an <span class="bold">alternative equivalent vehicle</span> in the similar segment as applicable.</li>
<li>The customer can request for amendments to a booking made earlier by him only if the request is<span class="bold"> done 10 hours before the pick-up time</span>. No changes will be done within 10 hours of the time of pick up time. In cases where amendments are requested on cab type, the cab type requested is subject to availability. In case of a no show where the customer has not informed " I SQUARE TAXI " on the changes on his schedule 10 hours before the pick-up no refunds will be made. The amendments can be done by contacting the support team of " I SQUARE TAXI " on 9043-99-6699 and mention the booking ID No for references.</li>
<li>The customer is liable to pay <span class="bold">waiting charges</span> in the case of delay (be it for any reason) exceeding more than 15 minutes from the scheduled pick up time.</li>
<li>The customer is liable to pay for any additional distance travelled and also for additional hourly charges if applicable. Any unscheduled changes will attract additional charges as applicable.</li>
<li>All bookings under consideration are on a calendar day basis i.e from <span class="bold">midnight 12:00 to midnight 12:00</span>. As an example for a cab booked for 4th July where the pick-up time is 4:00 p.m, the booking will be valid till 14th Apr 11:59 p.m and not 5th July 4:00 p.m.</li>
<li>Cabs that are booked for outstation (any or all of Oneway, round trip &amp; multicity) <span class="bold">cannot be used for local travel</span>. As an example if a customer books a cab from Chennai to Bangalore then to Nandi Hills and back to Chennai for a period of 3 days in total &amp; has a predefined Km limit of 800 Kms and he returns back to Chennai on the second day &amp; has a balance Km limit of 50 with one day remaining, in spite of this he is not entitled to consume this 50Kms for local travel in Chennai (From city), however the customer can travel from Chennai to some other city outside city limits of Chennai (say Chengalpet) &amp; consume the remaining 50 Kms or more than this by paying additional charges.</li>
<li>If needed, a customer can amend his booking from one way to round trip or from one way to multi-city while his travel is in progress. A request for the amendment while mentioning the booking ID number &amp; reason for amendment has to be made to the support team at " I SQUARE TAXI " by reaching them on 9043-99-6699. Whether or not to make an amendment as per the request of the customer solely rests with our support team. If the amendment request by the customer is approved our support team they will guide on the difference amount to be paid to the driver as to make the amendment a reality. This amount has to be paid immediately to the driver in cash after our team makes an amendment, failure to do so will not make the requested amendment a reality.</li>
<li>For all travel types (one way, round trip) customer has to bear all extra charges like driver allowance, toll, taxes, charges on for extra Kms consumed if applicable, charges for extra hours consumed if applicable, parking charges, night charges and any other charges applicable as <span class="bold">mentioned at the time of booking.</span></li>
<li>For one way outstation trips the customer will pay for any additional charges in the case where the driver needs to cover the additional distance (or) needs additional duration to complete his return journey (whichever of these two higher).</li>
<li>Transfers with unspecified distance coverage will only include one-way transfer either from airport or railway station to a single location or vice versa. Pick-ups or drops from multiple locations are not included in such bookings.</li>
<li>" I SQUARE TAXI " cannot be held accountable for any delay or consequential loss caused to the customer due to traffic jam or reasons beyond the reasonable control of the driver or lapses on the part of the driver.</li>
<li>" I SQUARE TAXI " cannot be held accountable for any loss, damage, physical injury etc suffered by the customer while availing its services.</li>
<li>In case of any <span class="bold">misconduct or misbehaviour by the driver</span>, the customer should <span class="bold">immediately report to the support team of " I SQUARE TAXI "</span> at 9043-99-6699 and share the experience while mentioning the booking ID No for reference.</li>
<li>" I SQUARE TAXI " cannot be held accountable for any loss, damage or delay suffered by the customer due to force majeure events.</li>
<li>In case of any dispute, parties agree to the exclusive jurisdiction of courts of Tamilnadu.</li>
<li>In addition to all the above-mentioned terms &amp; conditions, user terms mentioned on the website apply.</li>
<li>In a scenario, wherein a customer already has received the driver &amp; cab details and the cab hired does not show up on the day of travel, it will be considered as the failure of the fleet partner of " I SQUARE TAXI ". " I SQUARE TAXI " being a Taxi Booking Facilitator will take all necessary efforts to provide the customer with an alternative mode of transport immediately, in the shortest possible time. " I SQUARE TAXI " is not liable to reimburse its customer for any expenses<span class="bold"> like hotel stay charges, flight ticket charges or any other type of monetary expenses</span> which the customer had to bear as a result of no show of the cab on the day of planned cab travel.</li>
</ul>
<p><span class="bold">Special instructions</span></p>
<ul id="termsspecial">
<li>Driver &amp; car details - These details will be sent to the customer by " I SQUARE TAXI " <span class="bold">approximately before 4 hours from the pick-up time by SMS and email.</span> In some cases, the driver or an associate of " I SQUARE TAXI " may also call in advance to reconfirm with the customer.</li>
<li>Non-receipt of the driver and car details - In such cases the customer needs to contact the support team at " I SQUARE TAXI " on 9043-99-6699 and mention the booking ID number.</li>
<li>The demand of money by the driver- The booking ID provided to the customer clearly indicates the items including on his booking. Any amount over and above this both in terms of distance and duration and other items such as night charges, driver allowance, toll, taxes, state taxes, charges on for extra Kms consumed if applicable, charges for extra hours consumed if applicable, parking charges etc have to be paid directly to the driver in cash. In case of any dispute with the driver, the customer should reach the support team of " I SQUARE TAXI " at 9043-99-6699 and mention the booking ID details for reference and mention the subject of dispute.</li>
<li>Refusal by the driver to deliver services - The customer to contact the support team at " I SQUARE TAXI " on 9043-99-6699 and mention the booking ID number for reference.</li>
</ul>  
                </div>
              